server:
  port: 8080
  servlet:
    context-path: /api
spring:
  profiles:
    active: prod # local : 로컬 , prod : RDS
  jpa:
    properties:
      hibernate:
        show-sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
--- # 개발
spring:
  profiles: local
  datasource:
    url: jdbc:h2:tcp://localhost/~/bts;MODE=MYSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
--- # 배포
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://btsdb.czh6yt8bx4v6.ap-northeast-2.rds.amazonaws.com:3306/btsDB?serverTimezone=UTC&useSSL=false&characterEncoding=UTF-8
    username: admin
    password: btsbts123
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
--- # AWS S3
cloud:
  aws:
    credentials:
      accessKey: AKIAW5FCHZWRMVHQNGRB
      secretKey: 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
    s3:
      bucket: bts
    region:
      static: ap-northeast-2 # 서울
    stack:
      auto: false